---
title: The Saint-Exupéry ruler
categories: [combinatorial-optimization,integer-programming]
bibliography: references.bib
source: LeMonde
---

## Problem description

> *Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.*  
> — Antoine de Saint-Exupéry

The problem is to design a ruler of $n$ units using the fewest possible graduations, such 
that all possible integer lengths appear on the ruler.
This puzzle was published by Mickaël Launay [@lemonde2025saintExupery].

## MIP model

#### Parameters

- $N = \{0,1,\dots,n\}$: set of units of the ruler 

#### Variables

- $\textcolor{blue}{x}_i \in \{0,1\}$: takes value $1$ if and only if there is a mark on unit $i\in N$
- $\textcolor{blue}{y}_{i,j} \in \{0,1\}$: takes value $1$ if and only if there are marks on units $i\in N$ and $j\in N$, $i< j$

#### Objective function

The problem is to minimize the number of marks:

$$
\min \sum_{i \in N} \textcolor{blue}{x}_i
$$

subject to:

#### Constraints

- All possible integer lengths must appear somehow on the ruler:

$$
\sum_{i<j, \;j-i=k} \textcolor{blue}{y}_{i,j} \ge 1 \quad \forall k \in N, k>0 \tag{1}
$$

- Variables $\textcolor{blue}{x}_i$ and $\textcolor{blue}{y}_{i,j}$ must be consistent:

\begin{align}
\textcolor{blue}{y}_{i,j} &\le \textcolor{blue}{x}_i &\forall i<j \tag{2}\\
\textcolor{blue}{y}_{i,j} &\le \textcolor{blue}{x}_j &\forall i<j  \tag{3}\\
\textcolor{blue}{x}_i+\textcolor{blue}{x}_j &\le 1+\textcolor{blue}{y}_{i,j}
&\forall i<j \tag{4} \\
\end{align}

Constraints $(2)$ and $(3)$  enforce $\textcolor{blue}{y}_{i,j}=1\implies \textcolor{blue}{x}_i=1$ and $\textcolor{blue}{x}_j=1$,
constraints $(4)$ enforce the reciprocal relationship.

## Solution

Solving this problem with $n=20$ takes less than a second with CBC and yields:

{{< embed notebooks/saint_exupery_ruler.ipynb#75251953-f8df-4818-bdbd-9c2e93b00a20 >}}

So the 20 unit ruler can be designed with $8$ marks. We can check that all integer 
lengths do appear on the ruler (some lengths appear multiple times):

{{< embed notebooks/saint_exupery_ruler.ipynb#e835b29f-e67a-443b-9d3c-6cfe896b52e2 >}}
